name: Ryan Page
favicon: null
layout_spectrum: 0.7383900228887796
typography_spectrum: 0.7870814048219472
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#17BEBB'
    - '#2E282A'
    - '#CD5334'
    - '#EDB88B'
    - '#FAD8D6'
  brandStrength: 0.49784720432944596
  lightness: 0.12647883407771587
  saturation: 0.030903429491445422
  rhythmicContrast: 0.6535698852967471
purpose: []
